---
title: "Capstone Project"
author: "Oluwatobi Akinsola"
date: "2023-11-01"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Step 1
I installed and loaded the packages to be used for my analysis

```{r install packages}
install.packages("tidyverse")
install.packages("here")
install.packages("skimr")
install.packages("janitor")
install.packages("lubridate")
```
```{r load packages}
library(tidyverse)
library(here)
library(skimr)
library(janitor)
library(lubridate)
```
## Step 2
Importing data
```{r load library}
library(readr)
```
```{r import data}
daily_activity <- read.csv("dailyActivity_merged.csv")
daily_steps <- read.csv("dailySteps_merged.csv")
daily_sleep <- read.csv("sleepDay_merged.csv")
hourly_steps <- read.csv("hourlySteps_merged.csv")
hourly_calories <- read.csv("hourlyCalories_merged.csv")
hourly_intensities <- read.csv("hourlyIntensities_merged.csv")
weight <- read.csv("weightLogInfo_merged.csv")
```
```{r preview data}
head(daily_activity)
head(daily_steps)
head(daily_sleep)
head(hourly_steps)
head(hourly_calories)
head(hourly_intensities)
head(weight)
```
## step 3
Checking the structure of the data
```{r structure of the data}
str(daily_activity)
str(daily_steps)
str(daily_sleep)
str(hourly_steps)
str(hourly_calories)
str(hourly_intensities)
str(weight)

```
## Step 4
cleaning and formatting data
```{r numbers of particpant of each data}
n_unique(daily_activity$Id)
n_unique(daily_steps$Id)
n_unique(daily_sleep$Id)
n_unique(hourly_steps$Id)
n_unique(hourly_calories$Id)
n_unique(hourly_intensities$Id)
n_unique(weight$Id)

```
```{r checking for duplicate}
sum(duplicated(daily_activity))
sum(duplicated(daily_steps))
sum(duplicated(daily_sleep))
sum(duplicated(hourly_steps))
sum(duplicated(hourly_calories))
sum(duplicated(hourly_intensities))
```
```{r remove all duplicates and missing values}
daily_activity <- daily_activity %>%
  distinct() %>%
  drop_na()
daily_steps <- daily_steps %>%
  distinct() %>%
  drop_na()
daily_sleep <- daily_sleep %>%
  distinct() %>%
  drop_na()
hourly_steps <- hourly_steps %>%
  distinct() %>%
  drop_na()
hourly_calories <- hourly_calories %>%
  distinct() %>%
  drop_na()
hourly_intensities <- hourly_intensities %>%
  distinct() %>%
  drop_na()
```
```{r clean and rename columns}
clean_names(daily_activity)
daily_activity <- rename_with(daily_activity, tolower)
clean_names(daily_steps)
daily_steps <- rename_with(daily_steps, tolower)
clean_names(daily_sleep)
daily_sleep <- rename_with(daily_sleep, tolower)
clean_names(hourly_steps)
hourly_steps <- rename_with(hourly_steps, tolower)
clean_names(hourly_calories)
hourly_calories <- rename_with(hourly_calories, tolower)
clean_names(hourly_intensities)
hourly_intensities <- rename_with(hourly_intensities, tolower)
```


```{r clean format}
daily_activity <- daily_activity %>%
  rename(date = activitydate) %>%
  mutate(date = as_date(date, format = "%m/%d/%Y"))
daily_sleep <- daily_sleep %>%
  rename(date = sleepday) %>%
  mutate(date = as_date(date, format ="%m/%d/%Y %I:%M:%S %p", tz = Sys.timezone()))
hourly_calories <- hourly_calories %>% 
  rename(date_time = activityhour) %>% 
  mutate(date_time = as.POSIXct(date_time, format ="%m/%d/%Y %I:%M:%S %p" , tz=Sys.timezone()))
hourly_intensities <- hourly_intensities %>% 
  rename(date_time = activityhour) %>% 
  mutate(date_time = as.POSIXct(date_time, format ="%m/%d/%Y %I:%M:%S %p" , tz=Sys.timezone()))
hourly_steps<- hourly_steps %>% 
  rename(date_time = activityhour) %>% 
  mutate(date_time = as.POSIXct(date_time, format ="%m/%d/%Y %I:%M:%S %p" , tz=Sys.timezone()))

```
## step 5
```{r merging dataset}
daily_activity_sleep <- merge(daily_activity, daily_sleep, by=c ("id","date"))

```
## step 6
```{r summarize each dataset}
daily_activity %>%
  select(totalsteps,
         totaldistance,
         sedentaryminutes, calories) %>%
  summary()
```
## step 7
```{r visualization to check the correlation brtween the steps taken and the calories burned}
ggplot(data = daily_activity, aes(x = totalsteps, y = calories)) + geom_point(color = 'red') + geom_smooth() + labs(title ="Total Steps vs. Calories")
ggsave('Total_Steps vs. Calories.png')
```
## step 8
```{r steps per weekday}
weekday_steps <- daily_activity %>%
  mutate(weekday =weekdays(date))
weekday_steps$weekday <-ordered(weekday_steps$weekday,levels=c("Monday","Tuesday",
                               "Wednesday","Thursday","Friday","Saturday","Sunday"))
weekday_steps <-weekday_steps %>%
  group_by(weekday) %>%
  summarize(daily_steps = mean(totalsteps))

head(weekday_steps)
```
```{r visualiztion: Daily steps per weekday}
ggplot(weekday_steps, aes(weekday, daily_steps)) +
  geom_col(fill ='blue') +
  geom_hline(yintercept = 7500) +
  labs(title = "Daily steps per weekday", x= "", y= "") +
  theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1))
ggsave('Daily_steps per weekday.pdf')
  
```
## step 9
```{r sleep per weekday}
weekday_sleep <- daily_sleep %>%
  mutate(weekday =weekdays(date))
weekday_sleep$weekday <-ordered(weekday_sleep$weekday,levels=c("Monday","Tuesday",
                               "Wednesday","Thursday","Friday","Saturday","Sunday"))
weekday_sleep <-weekday_sleep %>%
  group_by(weekday) %>%
  summarize(daily_sleep = mean(totalminutesasleep))

head(weekday_sleep)

```
```{r visualiztion: Minutes asleep per weekday}
ggplot(weekday_sleep, aes(weekday, daily_sleep)) +
  geom_col(fill ='purple') +
  geom_hline(yintercept = 480) +
  labs(title = "Minutes asleep per weekday", x= "", y= "") +
  theme(axis.text.x = element_text(angle = 45,vjust = 0.5, hjust = 1))
ggsave('Minutes_asleep per weekday.pdf')

```
## step 10
```{r hourly_intensities visualization}
ggplot(data = hourly_intensities, aes(x= time, y = mean_total_int)) + 
  geom_histogram(stat = "identity", fill='pink') + 
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title = "Average Total Intensity vs. Time")
ggsave('Average_Total_Intensity vs. Time.pdf')

```
## step 11
```{r visualization of hourly steps throughout the day}
hourly_steps %>%
  group_by(time) %>%
  summarize(average_steps =mean(steptotal)) %>%
  ggplot() +
  geom_col(mapping = aes(x=time, y = average_steps, fill= average_steps)) +
  labs(title = "Hourly steps throughout the day", x="", y="") +
  scale_fill_gradient(low = "red", high = "blue") +
  theme(axis.text.x = element_text(angle = 90))
ggsave('Hourly steps throughout the day.pdf')

```
## step 12
```{r group data based on the number of days smart device was used}
daily_use <- daily_activity_sleep %>%
  group_by(id) %>%
  summarize(days_used=sum(n())) %>%
  mutate(user_type= case_when(
    days_used >= 1 & days_used <= 10 ~ "low user",
    days_used >= 11 & days_used <= 20 ~ "moderate user", 
    days_used >= 21 & days_used <= 31 ~ "high user", 
  ))

head(daily_use)


```

```{r percenage of each data frame}
daily_use_percent <- daily_use %>%
  group_by(user_type) %>%
  summarise(total = n()) %>%
  mutate(totals = sum(total)) %>%
  group_by(user_type) %>%
  summarise(total_percent = total / totals) %>%
  mutate(labels = scales::percent(total_percent))

daily_use_percent$user_type <- factor(daily_use_percent$user_type, levels = c("high user", "moderate user", "low user"))

head(daily_use_percent)


```

```{r visualization of smart device usage}
daily_use_percent %>%
  ggplot(aes(x = "",y = total_percent, fill = user_type)) +
  geom_bar(stat = "identity", width = 1)+
  coord_polar("y", start=0)+
  theme_minimal()+
  theme(axis.title.x= element_blank(),
        axis.title.y = element_blank(),
        panel.border = element_blank(), 
        panel.grid = element_blank(), 
        axis.ticks = element_blank(),
        axis.text.x = element_blank(),
        plot.title = element_text(hjust = 0.5, size=14, face = "bold")) +
  geom_text(aes(label = labels),
            position = position_stack(vjust = 0.5))+
  scale_fill_manual(values = c( "blue","purple","#fc9fb7"),
                    labels = c("High user - 21 to 31 days",
                               "Moderate user - 11 to 20 days",
                               "Low user - 1 to 10 days"))+
  labs(title="Daily use of smart device")
ggsave('Daily use of smart device.pdf')


```

































